export default {
  aries: [],
  taurus: [
    'do something.',
  ],
  gemini: [],
  cancer: [],
  leo: [],
  virgo: [],
  libra: [],
  scorpio: [
    "treat yourself to tiger's eye jewerly.",
    'get motivated.',
    'stay healthy with red ginseng.',
    'collect a glass figurine.',
    'get away from it all.',
    'do a flowing exercise.',
    'stick to a routine.',
    'carry tourmaline.',
    'take a bath.',
    'do water aerobics.',
    'do some stretches.',
    'watch your salt consumpton.',
    'try to drink more water.',
    'look at some pictures of snakes.',
    'collect some apothecary jars.',
    'go on a nature walk.',
    'listen to some water sounds.',
    'watch a funny movie.',
    'make youself laugh.',
    'avoid crowds and gatherings.',
    'visit a labyrinth.',
    'adopt a ferret.',
    'decorate your bathroom with a candle.',
    'listen to flamenco music.',
    'go stargazing.',
    'sleep in complete darkness.',
    'get cozy.',
    'listen to Drake.',
    'listen to Keith Urban.',
    'listen to Brad Paisley.',
    'listen to Frank Ocean.',
    'listen to Bjork.',
    'listen to Neil Young.',
    'cook something fancy.',
    'find some privacy.',
    'enjoy Pablo Picasso.',
    "enjoy Georgia O'Keeffe.",
    'enjoy Claude Monet.',
    'watch Bob Ross.',
    'sniff some Myrrh.',
    'use a sauna.',
    'go ice skating.',
    'try to learn something new.',
    'go boxing.',
    'write in your journal.',
    'take a photo.',
    'sleep to the sounds of water.',
    'surround yourself with ocean hues.',
    'look at some fish.',
    'try drawing something.',
    'learn how to tango.',
    'surround yourself with succulents.',
    'try meditation.',
    'do a crossword puzzle.',
    'drink some coffee.',
    'interact with a dog or a cat.',
    'spend time with your loved ones.',
    'try a mud bath.',
    'listen to an opera.',
    'embrace your love of history.',
    'investigate your past lives.',
    'trust your intuition.',
    'try chanting.',
    'try white magic.',
    'read a mystery book.',
    'watch a mystery movie.',
    'try photography.',
    'do a face mask.',
    'try writing a short story.',
    'keep a dream diary.',
    'dress in black.',
    'fix yourself a cocktail.',
    'start a collection.',
    'drink clove tea.',
    'visit a graveyard.',
    'kick a bad habit.',
    'eat some garlic.',
    'consume some probiotics.',
    'go for a jog.',
    'get a pyramid paperweight for your desk.',
    'learn how to play poker.',
    'try kickboxing.',
    "get a full night's sleep.",
    'find a good book to read.',
    'visit the water.',
    'visit a spa.',
    'do an intense workout.',
    'eat a full breakfast.',
    'order flowers for yourself.',
    'create a playlist.',
    'disconnect from social media.',
  ],
  sagittarius: [],
  capricorn: [],
  aquarius: [],
  pisces: [],
};
